max_memory_mb: 1024           # Maximum memory allocation in MB
max_script_size: 1024000      # Maximum script size in bytes 
server_port: 9997             # Server listening port
script_timeout: 3s            # Maximum script execution time 
worker_pool_size: 5           # Number of worker threads in the script execution pool
log_on_console: true          # Enable or disable logging to the console, file logging is always on
shutdown_allow_time: 5s       # Amount of time graceful shutdown are given, before executing hard shutdown.
shutdown_pause_time: 5s       # Amount of time to pause after a graceful shutdown.
